Project_ReisivadTöötajad/Project_ReisivadTöötajad/Models/Person.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ReisivadTöötajad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Travels = new HashSet<Travel>();
            this.UserInRoles = new HashSet<UserInRole>();
        }
    
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Person ID")] 

        [StringLength(11, ErrorMessage = "Person ID must be max 11 digits")] 
        public string PersonID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter First Name")]
         
        public string FirstName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Last Name")] 
        public string LastName { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)] 
        public System.DateTime StartDate { get; set; }
        public int PersonState { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Department Name")] 
        public int DepartmentID { get; set; }
        public Nullable<int> Picture { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter Email")] 
        public string Email { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travel> Travels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
        public virtual File File { get; set; }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_ReisivadTöötajad.Models;

namespace Project_ReisivadTöötajad.Models
{
    partial class Person
    {

        public static Dictionary<int, string> PersonStates = new Dictionary<int, string>
        {
            {0, "Currently Employed"},
            {1, "Has Left the Company"},

        };
        public string FullName => FirstName + " " + LastName;

        public static Person GetByEmail(string email)
        {
            //static 
                TagaridaEntities db = new TagaridaEntities();
            return db.People.Where(x => x.Email == email).SingleOrDefault();
        }

        public bool IsInRole(string rolename)
            => this.UserInRoles
                .Select(x => x.Role.RoleName.ToLower()).ToList()
                .Intersect(rolename.Split(',').Select(y => y.Trim().ToLower()))
                .Count() > 0;
    }
}

namespace Project_ReisivadTöötajad.Controllers  
{
    public class PersonController : Controller
    {
        private TagaridaEntities db = new TagaridaEntities();

        // GET: Person
        public ActionResult Index(int? personId, int? departmentId, int? stateId)
        {
            var loginUser = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();  //sisseloginu andmed

            if (loginUser == null || loginUser.PersonState == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Access Denied");
            }

            var people = db.People
                .Include(p => p.Department)
                .Include(p => p.File)
                .OrderBy(x => x.LastName).OrderBy(x => x.FirstName)
                .ToList();

            ViewBag.personId = new SelectList(db.People.OrderBy(x => x.LastName).OrderBy(x => x.FirstName), "Id", "FullName");
            ViewBag.departmentId = new SelectList(db.Departments.OrderBy(x => x.DepartmentName), "Id", "DepartmentName");
            ViewBag.PersonState = Person.PersonStates; //Sellega kuvatakse nimelised väärtused
            ViewBag.stateId = new SelectList(Person.PersonStates, "Key", "Value");

            /* ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
             db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Person;Index;Get;" + ";Person Id;" + "" + ";Full Name;" + "" + ";Department ID;" + "" + ";State;" + "" + ";Start Date;" + "" });
             db.SaveChanges(); */ //võtsin praegu välja                                                                            

            if (personId > 0)
            {
                people = people.Where(v => v.Id == personId).ToList();
            }

            if (departmentId > 0)
            {
                people = people.Where(v => v.Department.Id == departmentId).ToList();
            }

            if (stateId >= 0)
            {
                people = people.Where(v => v.PersonState == stateId).ToList();
            }

            return View(people);
        }

        public ActionResult AddRole(int? id, int? roleid)           // parameetritena defineeritakse Person tabeli id (töötaja id) ja Roles tabeli id (rolli id)
        {
            if (id == null)             // kontrollib, kui parameetiks olev id on tühi, siis annab veateate
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);             // defineerib Person tüüpi muutuja, millele omistatakse Person tabeli väljad, mis on seotud etteantud töötaja id-ga (id)
            if (person == null)                             // kui id vastet ei leia, siis annab veateate
            {
                return HttpNotFound();
            }

            if (roleid == null)         // kontrollib, kui parameetiks olev roleid on tühi, siis annab veateate
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Access Denied");
            }
            Role role = db.Roles.Find(roleid);              // defineerib Role tüüpi muutuja, millele omistatakse Role tabeli väljad, mis on seotud etteantud rolli id-ga (roleid)
            if (role == null)                               // kui roleid vastet ei leia, siis annab veateate
            {
                return HttpNotFound();
            }

            try
            {
                db.UserInRoles.Add(new UserInRole { PersonId = id.Value, RoleId = roleid.Value });   // Tabelisse UserInRoles lisatakse uus kirje
                db.SaveChanges();
            }
            catch { }

            ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
            db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Person;AddRole;;" + ";Person Id;" + person.Id + ";Full Name;" + person.FullName + ";Department ID;" + person.DepartmentID + ";State;" + person.PersonState + ";Start Date;" + person.StartDate });
            db.SaveChanges();

            return RedirectToAction("Edit", new { id = id });
        }

        public ActionResult RemoveRole(int? id, int? roleid)  // parameetritena defineeritakse Person tabeli id (töötaja id) ja Roles tabeli id (rolli id)
        {
            if (id == null)         // kontrollib, kui parameetiks olev id on tühi, siis annab veateate
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);      // defineerib Person tüüpi muutuja, millele omistatakse Person tabeli väljad, mis on seotud etteantud töötaja id-ga (id)
            if (person == null)                      // kui id vastet ei leia, siis annab veateate
            {
                return HttpNotFound();
            }

            if (roleid == null)         // kontrollib, kui parameetriks olev roleid on tühi, siis annab veateate
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userinrole = person.UserInRoles.Where(x => x.RoleId == roleid).FirstOrDefault();        // defineeritakse muutuja, mis tuletatakse töötaja id-st ja rolli id-st, mis on valitud
            if (userinrole != null)
            {
                db.UserInRoles.Remove(userinrole);          // userinrole kustutatakse UserInRole tabelist
                db.SaveChanges();
            }

            ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
            db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Person;RemoveRole;;" + ";Person Id;" + person.Id + ";Full Name;" + person.FullName + ";Department ID;" + person.DepartmentID + ";State;" + person.PersonState + ";Start Date;" + person.StartDate });
            db.SaveChanges();

            return RedirectToAction("Edit", new { id = id });
        }

        // GET: Person/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            ViewBag.OtherRoles = db
                .Roles
                .Where(x => !x.UserInRoles.Select(y => y.PersonId).Contains(id.Value)).ToList();

            /*ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
            db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Person;Details;Get;" + ";Person Id;" + person.Id + ";Full Name;" + person.FullName + ";Department ID;" + person.DepartmentID + ";State;" + person.PersonState + ";Start Date;" + person.StartDate });
            db.SaveChanges();*/ //Võtsin praegu välja

            return View(person);
        }


        // GET: Person/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Departments, "Id", "DepartmentName");
            //ViewBag.Picture = new SelectList(db.Files, "Id", "Filename");

            return View();
        }

        // POST: Person/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PersonID,FirstName,LastName,StartDate,DepartmentID,Email")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();

                ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
                db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Person;Create;Post;" + ";Person Id;" + person.Id + ";Full Name;" + person.FullName + ";Department ID;" + person.DepartmentID + ";State;" + person.PersonState + ";Start Date;" + person.StartDate });
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.DepartmentID = new SelectList(db.Departments, "Id", "DepartmentName", person.DepartmentID);
            //ViewBag.Picture = new SelectList(db.Files, "Id", "Filename", person.Picture);

            return View(person);
        }

        // GET: Person/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound(); 
            }
            ViewBag.OtherRoles = db

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Person/Create.cshtml
@model Project_ReisivadTöötajad.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Employee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.PersonID, "Person ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PersonID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PersonID, "Person ID must be max 11 digits", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "First Name is required", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "Last Name is required", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, "Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.PersonState, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonState, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonState, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "Department Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentID", null, "-- Select Department --", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "Department Name is required", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
            @Html.LabelFor(model => model.Picture, "Picture", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Picture", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "Email is required", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Person/Delete.cshtml
@model Project_ReisivadTöötajad.Models.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div>
    <h4>Employee</h4>
    <h4 style="color: red;">Are you sure you want to delete this?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Person ID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonID)
        </dd>

        <dt>
            @Html.DisplayName("First Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayName("Last Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayName("Start Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        @*<dt>
            @Html.DisplayName("Person State")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonState)
        </dd>*@

        <dt>
            @Html.DisplayName("Department Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        @*@{/* TODO: Ära jätta? */}
        <dt>
            @Html.DisplayNameFor(model => model.File.Filename)
        </dt>
        @{/* TODO: Ära jätta? */}
        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>*@

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Person/Details.cshtml
@model Project_ReisivadTöötajad.Models.Person

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Person ID")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonID)
        </dd>

        <dt>
            @Html.DisplayName("First Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayName("Last Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayName("Start Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        @*<dt>
            @Html.DisplayName("Person State")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonState)
        </dd>*@



        <dt>
            @Html.DisplayName("Department Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        @*@{/* TODO: Ära jätta? */}

        <dt>
            @Html.DisplayNameFor(model => model.File.Filename)
        </dt>
        @{/* TODO: Ära jätta? */}

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>*@

    </dl>
</div>



<h4>In Roles:</h4>
<ol>
    @foreach (var x in Model.UserInRoles)
    {
        <li> @Html.ActionLink((x.Role.RoleName), "RemoveRole", new { id = Model.Id, roleid = x.RoleId }, new { onclick = "javascript:return false;" }) </li>
        //Kui keegi leiab parema viisi, kuidas rolle kuvada, siis võib seda kasutada.
    }
</ol>




<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Person/Edit.cshtml
@model Project_ReisivadTöötajad.Models.Person

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Employee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.PersonID, "Person ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PersonID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PersonID, "Person ID must be max 11 digits", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "First Name is required", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "Last Name is required", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, "Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PersonState, "Person State", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.PersonState, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PersonState, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "Department Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "Department Name is required", new { @class = "text-danger" })
        </div>
    </div>
    @*@{/* TODO: Sellega tuleb midagi teha, kas ära jätta või eraldada see SpendingFiles'ist: */}
        <div class="form-group">
           @Html.LabelFor(model => model.Picture, "Picture", htmlAttributes: new { @class = "control-label col-md-2" })
           <div class="col-md-10">
               @Html.DropDownList("Picture", null, htmlAttributes: new { @class = "form-control" })
               @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
           </div>*@
    @*</div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "Email is required", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>

    <h4>In Roles:</h4>
    <ol>
        @foreach (var x in Model.UserInRoles)
        {
            <li> @Html.ActionLink(("- " + x.Role.RoleName), "RemoveRole", new { id = Model.Id, roleid = x.RoleId }) </li>
        }
    </ol>
    <h4>Not in Roles:</h4>
    <ol>
        @foreach (Project_ReisivadTöötajad.Models.Role x in ViewBag.OtherRoles)
        {
            @*<li> @Html.ActionLink(("+ "+x.RoleName), "AddRole", new { id = Model.Id, roleid = x.Id }) </li>*@
            <li> @Html.ActionLink("+ " + x.RoleName, "AddRole", new { id = Model.Id, roleid = x.Id }) </li>
        }
    </ol>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Person/Index.cshtml
@model IEnumerable<Project_ReisivadTöötajad.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Employees</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Person", FormMethod.Get))
{
    <p>
        <div class="row">
            <div class="col-sm-2"> @Html.DropDownList("personId", null, "-- Select Name --", htmlAttributes: new { @class = "form-control" }) </div>  @*list personID luuakse controlleris*@
            <div class="col-sm-2"> @Html.DropDownList("departmentId", null, "-- Select Department --", htmlAttributes: new { @class = "form-control" }) </div>  @*list departmentID luuakse controlleris*@
            <div class="col-sm-2"> @Html.DropDownList("stateId", null, "-- Select State --", htmlAttributes: new { @class = "form-control" }) </div>  @*list stateID luuakse controlleris*@

            <div class="col-sm-2"> <input type="submit" value="Search" class="btn btn-default" /></div>

        </div>

    </p>

}

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Full Name")
        </th>
        <th>
            @Html.DisplayName("Person ID")
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>*@
        <th>
            @Html.DisplayName("Start Date")
        </th>
        <th>
                @Html.DisplayName("Person State")
            </th>
        <th>
            @Html.DisplayName("Department Name")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*@if (item.PersonState != 1)*@
            
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PersonID)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @(((Dictionary<int, string>)ViewBag.PersonState)[item.PersonState]) @*Kuvatakse nimelise väärtusena*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department.DepartmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                    @* @Html.ActionLink("Delete", "Delete", new { id = item.Id }) *@
                </td>
            
        </tr>
    }

</table>