Project_ReisivadTöötajad/Project_ReisivadTöötajad/Models/Spending.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ReisivadTöötajad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Spending
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spending()
        {
            this.SpendingFiles = new HashSet<SpendingFile>();
        }
    
        public int Id { get; set; }
        public int TravelId { get; set; }
        public int TypeId { get; set; }
        [Required] 
        [Range(0, Double.PositiveInfinity)] 
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Document { get; set; }
        public string ServiceProvider { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)] 
        public Nullable<System.DateTime> StartDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)] 
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> VatEUR { get; set; }
        public bool PaidOut { get; set; }
    
        public virtual Travel Travel { get; set; }
        public virtual SpendingType SpendingType { get; set; }
        public virtual File File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpendingFile> SpendingFiles { get; set; }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Models/SpendingType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ReisivadTöötajad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpendingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpendingType()
        {
            this.Spendings = new HashSet<Spending>();
        }
    
        public int Id { get; set; }
        public string SpendingName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spending> Spendings { get; set; }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_ReisivadTöötajad.Models;

namespace Project_ReisivadTöötajad.Controllers
{
    public class FilesController : Controller
    {
        private TagaridaEntities db = new TagaridaEntities();

        public ActionResult Get(int? id)
        {
            if (!id.HasValue)
                return HttpNotFound();
            File file = db.Files.Find(id.Value);
            if (file == null)
                return HttpNotFound();

            return File(file.Content, file.ContentType);
        }


        // GET: Files
        public ActionResult Index()
        {
            return View(db.Files.ToList());
        }

        // GET: Files/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // GET: Files/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Content,Filename,ContentType")] File file)
        {
            if (ModelState.IsValid)
            {
                db.Files.Add(file);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(file);
        }

        // GET: Files/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,Filename,ContentType")] File file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(file).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(file);
        }

        // GET: Files/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            File file = db.Files.Find(id);
            db.Files.Remove(file);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Controllers/SpendingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_ReisivadTöötajad.Models;


namespace Project_ReisivadTöötajad.Controllers
{
    public class SpendingsController : Controller
    {
        private TagaridaEntities db = new TagaridaEntities();

        // GET: Spendings
        public ActionResult Index(int? travelid)
        {
            var loginUser = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();  //sisseloginu andmed

            if (loginUser == null || loginUser.PersonState == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Access Denied");
            }


            var spendings = db.Spendings
                .Include(s => s.File)
                .Include(s => s.Travel)
                .Include(s => s.SpendingType)
                .Where(t=> t.TravelId == travelid)
                ;

            if (travelid == null)         // kontrollib, kui parameetiks olev travelid on tühi, siis annab veateate
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //            Spending spending = db.Spendings.Find(travelid);      // defineerib Spending tüüpi muutuja, millele omistatakse Spending tabeli väljad, mis on seotud etteantud kulurea id-ga (id)


            ViewBag.TravelId = travelid;     // jätab travelid meelde, et hiljem saaks uut kulukirjet lisada ja sellele aktiivne travelid omistada
            ViewBag.TotalAmount = db.Spendings
                .Where(t => t.TravelId == travelid)
                .Sum(x => x.Amount);

            ViewBag.IconAfterText = " |";
            ViewBag.IconBeforeText = "| ";


            return View(spendings.ToList());
        }


        public ActionResult RemoveFile(int? spendingid, int? fileid)  // parameetritena defineeritakse Spending tabeli id (kulurea id) ja File tabeli id (file id)
        {
            if (spendingid == null)         // kontrollib, kui parameetiks olev spendingid on tühi, siis annab veateate
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(spendingid);      // defineerib Spending tüüpi muutuja, millele omistatakse Spending tabeli väljad, mis on seotud etteantud kulurea id-ga (id)
            if (spending == null)                      // kui id vastet ei leia, siis annab veateate
            {
                return HttpNotFound();
            }

            if (fileid == null)         // kontrollib, kui parameetriks olev fileid on tühi, siis annab veateate
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var spendingfile = spending.SpendingFiles.Where(x => x.FileId == fileid).FirstOrDefault();        // defineeritakse muutuja, mis tuletatakse spending id-st ja file id-st, mis on valitud
            if (spendingfile != null)
            {
                db.SpendingFiles.Remove(spendingfile);          // spendingfile (kombinatsioon spending id ja file id) kustutatakse SpendingFiles tabelist
                db.SaveChanges();
            }

            File deletefile = db.Files.Find(fileid);      //fileid järgi otsitakse File tabelist vastav rida ja kustutatakse see
            db.Files.Remove(deletefile);

            return RedirectToAction("Edit", new { id = spendingid });   
        }



        // GET: Spendings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }

            /*ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
            db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Spendings;Details;Get;" + ";Spending Id;" + spending.Id + ";Start Date;" + spending.StartDate + ";End Date;" + spending.EndDate + "Amount" + spending.Amount + "VAT" + spending.VatEUR });
            db.SaveChanges();*/ //Võtan praegu välja

            ViewBag.Icon = " |";

            return View(spending);
        }

        
        // GET: Spendings/Create
        public ActionResult Create(int travelid )
        {
            //if (spendingid == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            Spending spending = new Spending { TravelId = travelid };

            ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName");
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName");
            return View(spending);
        }

        // POST: Spendings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TravelId,TypeId,Amount,ServiceProvider,StartDate,EndDate,VatEUR")] Spending spending)
        {
            if (ModelState.IsValid)
            {
                db.Spendings.Add(spending);
                db.SaveChanges();

                TempData["Success"] = "Saved Successfully!";
                return RedirectToAction("Edit", "Spendings", new { id = spending.Id });
               // return RedirectToAction("Edit", new { id = spending.Id });
                //return RedirectToAction("Edit", new { id = spendingid });
            }

            //ViewBag.Document = new SelectList(db.Files, "Id", "Filename", spending.Document);
            ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName", spending.TravelId);
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);

            ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
            db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Spendings;Create;Post;" + ";Spending Id;" + spending.Id + ";Start Date;" + spending.StartDate + ";End Date;" + spending.EndDate + "Amount" + spending.Amount + "VAT" + spending.VatEUR });
            db.SaveChanges();
            
            return View(spending);
        }

        // GET: Spendings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }
            //ViewBag.Document = new SelectList(db.Files, "Id", "Filename", spending.Document);
            //ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName", spending.TravelId);
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);

            ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;
            db.ReportLogs.Add(new ReportLog { LogDate = DateTime.Now, UserID = ViewBag.UserId, LogRecord = "Spendings;Edit;Get;" + ";Spending Id;" + spending.Id + ";Start Date;" + spending.StartDate + ";End Date;" + spending.EndDate + "Amount" + spending.Amount + "VAT" + spending.VatEUR });
            db.SaveChanges();
            
            return View(spending);
        }

        // POST: Spendings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "Id,TravelId,TypeId,Amount,ServiceProvider,StartDate,EndDate,VatEUR")] Spending spending, HttpPostedFileBase file) // lisatud , HttpPostedFileBase file
        {
            if (ModelState.IsValid)
            {
                db.Entry(spending).State = EntityState.Modified;
                
           //     db.Entry(spending).Property(x => x.Document).IsModified = false;   //lisasime
                db.SaveChanges();

                //lisatud
                if (file != null && file.ContentLength > 0)
                {
                    using (System.IO.BinaryReader br = new System.IO.BinaryReader(file.InputStream))
                    {
                        //// ma lihtsuse mõttes kustutan vana pildi baasist
                        //File v = db.Files.Find(spending.Document ?? 0);
                        
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        File f = new File { Content = buff, ContentType = file.ContentType, Filename = file.FileName.Split('\\').Last().Split('/').Last() };
                        db.Files.Add(f);
                        db.SaveChanges();
                        spending.Document = f.Id;
                        db.SaveChanges();

                        db.SpendingFiles.Add(new SpendingFile { SpendingId = spending.Id, FileId = f.Id });   // Tabelisse SpendingFiles lisatakse uus kirje
                        db.SaveChanges();

                        //if (v != null)
                        //{
                        //    db.Files.Remove(v);
                        //    db.SaveChanges();
                        //}
                    }
                } //lisatud
               
                ViewBag.UserId = Person.GetByEmail(User.Identity.Name).Id;

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Spendings/Delete.cshtml
@model Project_ReisivadTöötajad.Models.Spending

@{
    ViewBag.Title = "Delete";
}

<h2>Delete spending</h2>
<div>
    @Html.ActionLink("Back to Application", "Edit", "Travels", new { id = Model.TravelId }, null)
</div>

<h4 style="color: red;">Are you sure you want to delete this?</h4>
<div>
    @*<h4>Spending</h4>*@
    <hr />
    <dl class="dl-horizontal">




        @*<dt>
            @Html.DisplayName("Travel Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.TravelName)
        </dd>*@

        <dt>
            @Html.DisplayName("Spending Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpendingType.SpendingName)
        </dd>
@if (Model.SpendingType.Id != 5)
{
    <dt>
            @Html.DisplayName("Service Provider")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceProvider)
        </dd>
}

        <dt>
            @Html.DisplayName("Start Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayName("End Date")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayName("Amount (incl VAT), EUR")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        @if(Model.SpendingType.Id != 5)
         {
        <dt>
            @Html.DisplayName("VAT Amount, EUR")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VatEUR)
        </dd>
        }
        @*<dt>
            @Html.DisplayName("Daily Allowance")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Travel.DailyAllowance)
        </dd>*@
        @*<dt>
            @Html.DisplayNameFor(model => model.File.Filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>*@

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            @*@Html.ActionLink("Back to List", "Index")*@
        </div>
    }
</div>

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Spendings/Details.cshtml
@model Project_ReisivadTöötajad.Models.Spending

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Spending</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayName("Spending Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayName("Travel Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.Id)
        </dd>*@

        @*<dt>
            @Html.DisplayName("Travel Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.TravelName)
        </dd>*@

        <dt>
            @Html.DisplayName("Spending Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpendingType.SpendingName)
        </dd>

@if (Model.SpendingType.Id != 5)
{
        <dt>
            @Html.DisplayName("Service Provider")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceProvider)
        </dd>
}

        <dt>
            @Html.DisplayName("Start Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayName("End date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayName("Amount (incl VAT), EUR")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        @if (Model.SpendingType.Id != 5)
        {
        <dt>
            @Html.DisplayName("VAT Amount, EUR")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VatEUR)
        </dd>

        }
        @*<dt>
            @Html.DisplayName("Daily Allowance")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.DailyAllowance)
        </dd>*@
        @*<dt>
            @Html.DisplayName("Paid Out")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaidOut)
        </dd>*@
        @*<dt>
            @Html.DisplayNameFor(model => model.File.Filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>*@
    </dl>
</div>


@if (Model.Document != null)
{
    <div>
        <img src="@Url.Action("Get", "Files", new { id = Model.Document })" height="120" />
    </div>
}

@*using (Html.BeginForm("AddPicture", "People", FormMethod.Post, new { enctype = "multipart/form-data" }))*@

    <p>
        @if (Model.SpendingType.Id != 5 && Model.Travel.ReportState !=5)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) @ViewBag.Icon
}
        @Html.ActionLink("Back to List", "Details", "Travels", new { id = Model.TravelId }, null)
    </p>

Project_ReisivadTöötajad/Project_ReisivadTöötajad/Views/Spendings/Edit.cshtml
@model Project_ReisivadTöötajad.Models.Spending

@{
    ViewBag.Title = "Edit";
}

<h2>Spending</h2>
<div>
    @Html.ActionLink("Back to Application", "Edit", "Travels", new { id = Model.TravelId }, null)
</div>

@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
}

@using (Html.BeginForm("Edit", "Spendings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Spending</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TravelId)
        @Html.HiddenFor(model => model.Travel.DailyAllowance)

        @*<div class="form-group">
            @Html.LabelFor(model => model.Id, "Spending Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })    väli on mitteaktiivne ja readonly

            </div>
        </div>*@


        @*<div class="form-group">
            @Html.LabelFor(model => model.TravelId, "TravelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{/* TODO: Dropdown list eemaldada */}
                @Html.DropDownList("TravelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TravelId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.TravelId, "Travel ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TravelId, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })    väli on mitteaktiivne ja readonly
                @Html.ValidationMessageFor(model => model.TravelId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @*<div class="form-group">
            @Html.LabelFor(model => model.Travel.TravelName, "Travel Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Travel.TravelName, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Travel.TravelName, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.TypeId, "Spending Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeId", null, "-- Select Spending Type --", htmlAttributes: new { @class = "form-control", @onchange = "getDates(this)" })  @*getDates(this)*@
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceProvider, "Service Provider", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceProvider, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceProvider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, "Start Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, "End Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, "Amount (incl VAT), EUR", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "Amount cannot be negative", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Travel.DailyAllowance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Travel.DailyAllowance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Travel.DailyAllowance, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.VatEUR, "VAT Amount, EUR", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VatEUR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VatEUR, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.PaidOut, "Paid Out", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.PaidOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaidOut, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @*<div class="form-group">
            @Html.LabelFor(model => model.Document, "Document", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Document", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <h5>Seotud failid:</h5>
        <ol>
            @foreach (var x in Model.SpendingFiles)
        {
            <li>
                <td>
                    @Html.ActionLink((x.File.Filename), "Get", "Files", new { id = x.FileId }, new { target = "_blank" })  @*FilesControlleris käivitab meetodi Get; new { target = "_blank" } avab dokumendi uues aknas*@
                    @Html.ActionLink(("Delete"), "RemoveFile", new { spendingid = Model.Id, fileid = x.FileId }, new { @class = "text-danger" })

                </td>
            </li>
    }
        </ol>

        <br />
        <h5> Add new file: </h5>
        <input type="file" name="file" id="file" />

        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}